### PR TITLE
Fixes issue #1235 - Run TCK using JDK 8

### LINKED ISSUE #1235: Run TCK using JDK 8
The signature tests require that the TCK run on JDK 8 and there are some tests that require the class sun.misc.InnocuousThread that was removed on JDK 9+.

To do so it is necessary to compile the Servlet API with JDK 8 too.

### PR DESCRIPTION
**Pull request by Thihup**
Fixes #1235

I have changed from endorsed lib to Xbootclasspath/a to be able to run the TCK with both JDK 8 and 15.
Unfortunately, the setup-java only exposes the JAVA_HOME pointing to the JDK 8 with version, so I had to fix the JDK 8 version to the 265 to avoid having to change the pom.xml each new release of JDK 8.

### CODE REVIEW

**Comment by manorrock** [comment]
Looking at the changes I have one question. This only changes the build for the Servlet API module, right? And then the TCK changes are checking it just for the signature, right?

**Comment by Thihup** [comment]
The TCK needs to be run with JDK 8 because it uses both static and reflection checks to see if the API is OK.
With JDK 15, the reflection check doesn't work because of some classes that were added to the hierarchy of some superclasses (like the java.lang.Enum) and changes to some annotations (like the Deprecated).

And there are the HTTP2 tests that use a class that doesn't exist anymore in the JDK, like the sun.misc.InnocuousThread.
Because of these failures, we need to run the TCK with the JDK 8, but the server still can be run with the latest JDK.

So yes, I only changed the Servlet API because the JDK 8 cannot read classes built with newer Java versions. This way both static checks and reflection checks pass. 

One example is Pages TCK. We are using the API that was built with the JDK 8 but even if the API is being built with JDK 8 the signature checks fail. Running the TCK with JDK 8 the checks passes.

We can still run the TCK with JDK 15 in our machines, but the signature tests will fail as well as the HTTP 2 tests.

**Comment by manorrock** [comment]
So can we run the TCK (ignoring the signature tests) using Java 15 and then have another run with Java 8 in the same workflow?

**Comment by Thihup** [comment]
I guess so. I'll give it a try

**Comment by Thihup** [comment]
Not as easy as I thought.
We need to compile with JDK 15 and run with both 15 and 8. To the TCK run with JDK 8, we need to change JDK used to start the Ant. 
We cannot rely on the JAVA_HOME because if it set, both Ant and Piranha will use it. If it is specified to JDK 8, Piranha won't start.
Probably we will need to use some trick with the JAVA_HOME_8_0_265_X64...

**Comment by manorrock** [comment]
OK lets take a step back! What about

1) Compile just the Servlet API with JDK 8 and run the signature tests with it
2) Run the entire TCK with Java 15 and we exclude signature tests and any other tests that are broken because of not working on a Java version > JDK 8?

Is that feasible?

**Comment by Thihup** [comment]
Let's split it then. I'll open a PR only changing the Servlet API to compile with JDK 8.

**Comment by Thihup** [comment]
I just found out that we can read the JDK path set by the setup-java using `${{steps.id.outputs.path}}`.
This way we can use it to set some property, like `ant.java.home` and run with both JDK 8 and JDK 15.
Can you have a look at the changes? What do you think?

**Comment by manorrock** [comment]
If that works it is fine by me.

**Pull request merged**
