### PR TITLE
Fixes issue #1487 - Update workflows to Java 16 when it is released

### LINKED ISSUE #1487: Update workflows to Java 16 when it is released

### PR DESCRIPTION
**Pull request by Thihup**
Fixes #1487

### CODE REVIEW

**Comment by Thihup** [comment]
Well, looks like we've got some building problem

**Comment by manorrock** [comment]
We'll have to wait a bit for Azul to deliver their Java 16 release as that is what GitHub Actions uses

**Comment by Thihup** [comment]
The building is failing the maven-shade-plugin saying that it doesn't support bytecode 60. Probably updating the ASM dependency should do the work. But why didn't it fail while we were using the 16-ea?

**Comment by manorrock** [comment]
Mmm, interesting

**Comment by manorrock** [comment]
See if setting the Maven Shade plugin to 3.3.0-SNAPSHOT fixes the problem. If it does we'll have to wait until the 3.3.0 version of the plugin has been released.

**Comment by Thihup** [comment]
I didn't try out the maven shade plugin 3.3.0-SNAPSHOT, but it looks they will update the Asm dependency. For now, we can work around it by updating the Asm, as we already do for the 'maven-plugin-plugin'.

**Review by manorrock — APPROVED** [review]

**Pull request merged**
