### PR TITLE
Fixes issue #1470 - Add --illegal-access=permit to run the tests

### LINKED ISSUE #1467: Weld doesn't seem to run on JDK 16ea
Running an application using Weld and Piranha Micro on JDK 16ea results in the following exception:

```
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @13d1f898
16380
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
16381
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
16382
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
16383
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
16384
	at org.jboss.weld.util.bytecode.ClassFileUtils$1.run(ClassFileUtils.java:67)
16385
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
16386
	at org.jboss.weld.util.bytecode.ClassFileUtils.makeClassLoaderMethodsAccessible(ClassFileUtils.java:60)
16387
	at org.jboss.weld.bootstrap.WeldStartup.startContainer(WeldStartup.java:220)
16388
	at org.jboss.weld.bootstrap.WeldBootstrap.startContainer(WeldBootstrap.java:72)
16389
	at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize(WeldServletLifecycle.java:180)
16390
	at org.jboss.weld.environment.servlet.Listener.contextInitialized(Listener.java:120)
16391
	at cloud.piranha.cdi.weld.WeldInitializer.onStartup(WeldInitializer.java:64)
```

### LINKED ISSUE #1470: Add --illegal-access=permit to run the tests

### PR DESCRIPTION
**Pull request by Thihup**
Fixes #1470
Fixes #1467

### CODE REVIEW

**Comment by lulseged** [comment]
It doesn't work on java 16.

**Comment by lulseged** [comment]
Java is now strongly encapsulated. That is why it dowsn't work in java 16.

java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @36ae8b84

**Comment by Thihup** [comment]
@lulseged This error was fixed in Piranha 21.4.0. Are you using this version?

**Comment by lulseged** [comment]
No.

**Comment by Thihup** [comment]
Could you please give it a try?

**Pull request merged**
