### PR TITLE
Fixes issue #1247 - Copy attributes from the session manager to the session cookie

### LINKED ISSUE #1247: Copy attributes from the session manager to the session cookie

### PR DESCRIPTION
**Pull request by Thihup**
Fixes #1247 

There is some discussion about the default value of _getName()_ in https://github.com/eclipse-ee4j/jakartaee-tck/pull/567.
We may need to revisit it later.

### CODE REVIEW

**Comment by manorrock** [comment]
Unfortunately the Snoop test is failing

**Comment by manorrock** [comment]
Cool discussion :)

**Comment by Thihup** [comment]
Looks like the snoop test is using the Jakarta servlet-api and their implementation throws NPE if null is passed as an argument. 
https://github.com/eclipse-ee4j/servlet-api/blob/master/api/src/main/java/jakarta/servlet/http/Cookie.java#L183

I think it is a bug in the Jakarta servlet-api. I can change to our implementation of the servlet API. Or I can add some null checks before the _setDomain_

**Comment by manorrock** [comment]
It should use ours ;)

**Pull request merged**
