### PR TITLE
Fixes issue #1305 - Run applications in a JPMS way

### LINKED ISSUE #1305: Run applications in a JPMS way
This is mostly an experimental thing. Current the Servlet (and any other) spec doesn't define how a container should handle a JPMS application.

I'd like to see if maybe we could get something workable and maybe help the specs in how the behavior should be.

I have been playing around and the java.lang.module API is very complex. The API contains the class ModuleFinder who can find the modules, but it only handles Paths ([ModuleFinder.html#of(java.nio.file.Path...)](https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/lang/module/ModuleFinder.html#of(java.nio.file.Path...)), making it filesystem dependant.

Ideally, we should use this API because it's implementation does exactly what we are used to. However, the can create our own ModuleFinder that doesn't depend on the JDK implementation. This way, we can create a ModuleFinder for "wars", and define our own concept of some features, like "patch-module" and were the module-info will be located (in the root of the war, in the WEB-INF/classes/module-info) and so on.

In this case, it would be implemented using layers, so an application server could implement it even it's underlying runtime doesn't use JPMS.

Sure that this is a long topic. We may even propose another file format, like "mar" to be a modular war to not be confused with the current behavior of the wars.

Comments?

### PR DESCRIPTION
**Pull request by Thihup**
An overview:
- The use of the JPMS layers can be disabled with "cloud.piranha.jpms.layers.disable"
- It is added as a "layer" on top of the existent classloader, so the classloading behavior shouldn't change
- An application with classes in the WEB-INF/classes with have the module name "classes" (Piranha Server) or application.war.classes (Piranha Micro)
- It has to work with split packages due to the Servlet TCK, so if it happens, the invalid modules goes to the unnamed module
- To be able to derive the module name was needed to add a Resource::getName method
- I couldn't figure out the best way to name the new module (cloud.piranha.jpms?)
- It needs support for multi-release jars (other places needs it too)
- Add support for user control the layers (something like `-Dpiranha.jmps.add.opens="foo/bar=baz"`)
- Both Exousia and Weld needs an additional change in the layer to be able to work. In JDK 16 it will require to add the flag in the comment (MicroOuterDeployer.java)
- For now, it is allowing the "UUID" from an application running from the Arquillian to be mapped to a module. The JDK implementation doesn't allow UUIDs as modules

Fixes #1305

### CODE REVIEW

**Comment by manorrock** [comment]
Some comments

* Can cloud.piranha.jpms.layers.disable be cloud.piranha.modular.disable?
* Is it possible for module name "classes" (Piranha Server) or application.war.classes (Piranha Micro) to be "cloud.piranha.modular.classes" ?
* Can the module name be "cloud.piranha.modular"
* Can -Dpiranha.jmps.add.opens="foo/bar=baz" be -Dpiranha.modular.add-opens="foo/bar=baz"?

This is really exciting to see. Great job!

**Comment by Thihup** [comment]
> * Can cloud.piranha.jpms.layers.disable be cloud.piranha.modular.disable?

Sure

> * Is it possible for module name "classes" (Piranha Server) or application.war.classes (Piranha Micro) to be "cloud.piranha.modular.classes" ?

For Piranha Micro it is easy to change from application.war.classes to "cloud.piranha.modular.classes", however for Piranha Server it is a little harder because it uses the folder name, and the folder name is "classes". I couldn't figure it out the best way to change it. But this is the name is of the user code, is it good to say it is from Piranha?

> * Can the module name be "cloud.piranha.modular"

Sure. How about the groupId and artifactId?

> * Can -Dpiranha.jmps.add.opens="foo/bar=baz" be -Dpiranha.modular.add-opens="foo/bar=baz"?

I haven't implemented this feature yet. But sure, the property can be the new name.

**Comment by manorrock** [comment]
* Not sure if it is possible, but can you do something similar to AliasedDirectoryResource for the Piranha Server case?
* GroupId cloud.piranha.modular and artifactId cloud.piranha.modular as well. To allow for growth (other use cases) we should create a parent POM project with groupId cloud.piranha.modular' and artifactId 'project' and stick the cloud.piranha.modular project in it.

**Comment by Thihup** [comment]
Done. I've added a new wrapper "AlisedNamedResource", that allows specifying the name of the resource.

**Comment by manorrock** [comment]
The web applications do not need to be modular now by default, right?

**Comment by Thihup** [comment]
Sure. Maybe change from `cloud.piranha.modular.disable` to `cloud.piranha.modular.enable`, so it would not be enabled by default. What do you think?

**Comment by manorrock** [comment]
And once the release is out the door may I suggest you write a blog entry for our blog so we can feature this?

**Comment by Thihup** [comment]
I'll add a manifest entry to Piranha Micro so it will not be required to specify manually `--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.security.provider=ALL-UNNAMED`

**Comment by Thihup** [comment]
I've noticed we still export the jakarta.servlet classes from own module (cloud.piranha.servlet.api) instead of the name of the official API (jakarta.servlet). Do you think we can change it before the release?
This way, one will necessarily require the usage of our servlet api jar, and would not be able to use the "default".

**Comment by manorrock** [comment]
Lets address the Servlet API question in a separate PR ;). Is this PR now ready to be merged?

**Comment by Thihup** [comment]
Sure. I guess so unless you have some other comments about it ;)

**Pull request merged**
