### PR TITLE
Fixes issue #1414 - Blog entry for the modular feature

### LINKED ISSUE #1414: Blog entry for the modular feature
I'm planning to create a simple example of creating a Servlet to displaying the module and that is possible to use the module-info to provide service implementations (in the case I'm thinking of using the ServletContainerInitializer).

Is there something special you would like to see in this post, like trying out another feature or using other libraries?

### PR DESCRIPTION
**Pull request by Thihup**
Fixes #1414

Feedbacks are welcome :)

### CODE REVIEW

**Comment by arjantijms** [comment]
Looks good! Maybe consider adding a few words about what the advantage is to make apps modular, or perhaps just that it's a unique feature of Piranha for now not found elsewhere etc.

Let's merge it first though to see what it looks like ;)

**Comment by arjantijms** [comment]
It doesn't really seem to work right now. Alternatively, maybe copy this page:

https://github.com/piranhacloud/piranha/blob/gh-pages/press-releases/mannorrock-announces-piranha.html

Which can be requested via:

https://piranha.cloud/press-releases/mannorrock-announces-piranha

For syntax highlighting, try https://tohtml.com/java/ with font 

```
<style>
@import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono&family=Waiting+for+the+Sunrise&display=swap');
</style>
```

**Comment by Thihup** [comment]
I guess @manorrock fixed something and now it is working 🎉 : `https://piranha.cloud/blog/2021/20210128_Modular_applications_with_JPMS`

**Comment by manorrock** [comment]
For future reference, the blog entry does need the .md extension to be processed, but then when mentioning the link you can either use the .html or completely drop it as the link above illustrate, both will show the same page. So when we announce and link anywhere we'll use the extensionless link ;)

**Comment by manorrock** [comment]
Note if you want to tackle creating a GitHub Pages theme akin to our main page I would be all for it (probably best to experiment with a throw away project if you decide to take that on ;))

**Pull request merged**
