### PR TITLE
Fixes issue #1022 - Add module-info.java to all our JARs

### LINKED ISSUE #1022: Add module-info.java to all our JARs

### PR DESCRIPTION
**Pull request by Thihup**
Fixes #1022

### CODE REVIEW

**Comment by manorrock** [comment]
@Thihup Looking good and great work!

**Review by arjantijms — APPROVED** [review]
Looks good!

**Comment by ggam** [comment]
I'm a bit late but shouldn't modules start with `cloud.piranha` instead of just `piranha`?

**Comment by arjantijms** [comment]
@ggam Might be a good suggestion indeed, especially if we want to set the convention that modules should as much as possible be named after their (main) package.

@Thihup @manorrock what do you think?

**Comment by manorrock** [comment]
I am fine if we change it to `cloud.piranha`. @Thihup Can you take care of that using a new issue?

**Comment by Thihup** [comment]
@arjantijms I think that's a good idea. 

@manorrock Yes, I can.

**Comment by ggam** [comment]
Thanks everyone!

**Pull request merged**
