### PR TITLE
Fixes issue #989 - Remove Jersey module

### LINKED ISSUE #989: Remove Jersey module
Blocked on #714

### PR DESCRIPTION
**Pull request by Thihup**
Fixes #989

### CODE REVIEW

**Comment by manorrock** [comment]
We should not directly have to use the org.glassfish.jersey.servlet.init.JerseyServletContainerInitializer, but instead use cloud.piranha.webapp.scinitializer.ServletContainerInitializerExtension and let it take care of adding the Jersey specific class automatically.

**Comment by Thihup** [comment]
We might face some problems because of the initialization of Weld by JakartaSecurityInitializer and by the Weld initializer. I'll do some tests

**Comment by Thihup** [comment]
The ServletContainerInitializerExtension initializes Jersey correctly. However, we've got some problems with CDI as I thought.
The extension initializes the _org.jboss.weld.environment.servlet.EnhancedListener_ before our _WeldInitializer_ (it is included by the JakartaSecurityAllInitializer).

**Comment by manorrock** [comment]
I noticed you did another commit .. does this mean it now works?

**Comment by Thihup** [comment]
Yes, I forget to comment here. Now it is working because we initialize Weld first.

**Comment by manorrock** [comment]
Sweet! Thanks for all the hard work :)

**Pull request merged**
