### PR TITLE
Fixes issue #855 - Fix ServletBasicTest

### LINKED ISSUE #855: Fix ServletBasicTest

### PR DESCRIPTION
**Pull request by Thihup**
Fixes #855

### CODE REVIEW

**Comment by manorrock** [comment]
Mea culpa for not describing this enough. As this particular tests has all the source code in our own tree it should belong in the test directory. E.g. test/arquillian. The external directory is for automatically pulling in external sources and running our server runtime against it. Other than the location looking good!

**Comment by Thihup** [comment]
Oh sorry, I have misunderstood what the external directory means. 
Unfortunately, as this test starts the Arquillian container, it will search for all dependencies in the remote repository and then the local repository. However, as we don't install the dependencies it will always fail. That's why I have created a Github action to run the "integration" tests and moved this test there.
Moving the test to the `test/arquillian` won't help either, because it will run only with `mvn verify` in the Github Actions, causing the _MavenResolver_ in MicroOuterDeployer never find the Piranha dependencies.
Most of the tests that are disabled require the dependencies to be in the repository. I'm not sure how to proceed.

**Comment by manorrock** [comment]
I have changed the build pipeline to use `install` instead of `verify`

**Comment by Thihup** [comment]
Alright! I'll move to the `test/arquillian` directory

**Pull request merged**
