### PR TITLE
Fixes issue #714 - Add HandlesTypes functionality

### LINKED ISSUE #714: Add HandlesTypes functionality

### PR DESCRIPTION
**Pull request by Thihup**
Fixes #714

### CODE REVIEW

**Comment by manorrock** [comment]
Thanks for the great work!

**Comment by manorrock** [comment]
Can you see if you can replace the Jersey initializer with the ServletContainerInitializer extension and then validate it indeed bootstraps Jersey?

**Comment by Thihup** [comment]
I have tested using the _org.glassfish.jersey.servlet.init.JerseyServletContainerInitializer_ instead of our JerseyInitializer it indeed started Jersey.
The Mojarra and Myfaces won't work right away because we don't scan all the annotated classes it requires but for JAX-RS, it is only four classes.

**Comment by manorrock** [comment]
Actually we should not directly have to use the org.glassfish.jersey.servlet.init.JerseyServletContainerInitializer, but instead use `cloud.piranha.webapp.scinitializer.ServletContainerInitializerExtension` and let it take care of adding the Jersey specific class automatically

**Comment by Thihup** [comment]
Alright! I do some more tests and change to use the ServletContainerInitializerExtension

**Pull request merged**
