### PR TITLE
Fixes issue #936 - Implement micro-profile extension

### LINKED ISSUE #936: Implement micro-profile extension
This extension delivers the minimal functionality for every Micro Profile module.

The following technologies need to be enabled.

1. CDI (Weld)
2. JAX-RS (Jersey)
3. JSON-B (Yasson)

### PR DESCRIPTION
**Pull request by Thihup**
I'd like some review about REST annotations, I couldn't understand why they were disabled to handle later. Maybe @arjantijms can give some hints?

Fixes #936

### CODE REVIEW

**Comment by arjantijms** [comment]
@Thihup I think you're referring to the annotation scanner in the core of MicroProfile. It now scans for a set number of annotations, which means that for the REST annotations core would need to have a dependency on Jakarta REST, which is unwanted, as REST comes in via an extension.

I wasn't yet sure how to handle this.

The scanner could index each and every annotation it encounters, but that's probably a bit too much.

It could also cheat a little by having the well known annotation classes in string names and looking at the class names, but that's... well, not so nice.

Yet another alternative is having extensions in some service file or the other specify which annotations need to be indexed, so the scanner can look for these and add them to the index.

The last option is probably the best, but at the point of disabling the annotations I just hadn't given it much thought yet.

**Comment by Thihup** [comment]
What if each extension returns a set containing all the required classes to work exposing through ServiceLoader? This way the REST can return the classes it needs to scan, the WebAnnotation can returns which depends, and so on.

**Comment by arjantijms** [comment]
>  What if each extension returns a set containing all the required classes to work exposing through ServiceLoader? This way the REST extension can return the classes it needs to scan, the WebAnnotation extension can returns which depends, and so on.

Sounds good, that's maybe even better than a separate file.

**Comment by Thihup** [comment]
> Does the micro-profile extension deliver everything the micro-core extension delivers and the additional functionality needed for MicroProfile, or does it need the micro-core extension? If it currently needs the micro-core extension it needs to change to be standalone so our MicroProfile users do not need to specify anything more than the micro-profile extension

@manorrock Can I just add the dependency on micro-core? This way it will work without need to specify the micro-core extension, just the micro-profile.

**Pull request merged**
