### PR TITLE
message added for the same ports for Micro

### PR DESCRIPTION
**Pull request by salmansharifov**
## Required

Associated issue: #2620

### CODE REVIEW

**Comment by salmansharifov** [comment]
@Thihup Can you review my mr please? Thanks

**Comment by Thihup** [comment]
Hi @salmansharifov 

As this is your first PR can you please acknowledge that the code will be owned by Manorrock.com. I will only ask this one time as that is all that is needed for contributing code back to us.

**Comment by salmansharifov** [comment]
Hi @Thihup 
No problem.

**Comment by mnriem** [comment]
@salmansharifov Unfortunately 'no problem' is not enough as an acknowledgement. Please say something like 'I acknowledge the code will be owned by Manorrock.com' and then we can proceed to merge your first contribution which is very much appreciated!

**Comment by salmansharifov** [comment]
I acknowledge the code will be owned by Manorrock.com

**Comment by mnriem** [comment]
@Thihup Go ahead and merge at your discretion!

**Review by mnriem — APPROVED** [review]

**Comment by Thihup** [comment]
@salmansharifov Thank you for your contribution!

**Pull request merged**
