### PR TITLE
Little refactoring of PiranhaServerContainerConfiguration

### PR DESCRIPTION
**Pull request by amihaiemil**
I've made some changes to class PiranhaServerContainerConfiguration from the arquillan package:

1. Added constructors. I think it's cleaner this way. Also notice the ctors are cascading - it's a good practice in OOP to have a single ctor that actually initializes the variables. If a class really needs to have more initializing constructors (more ways of creation), then the design is probably flawed.

2. Used ``this.`` in every place where attributes are being used.

3. Renamed lambda variables from ``e`` to what they actually are.

4. Small indentation changes inside method validate()

### CODE REVIEW

**Comment by amihaiemil** [comment]
@arjantijms this class also has a problem. The validate() method doesn't actually do any validations from what I can see. It's actually an init method :)

**Comment by arjantijms** [comment]
Thanks for the PR.

I'll comment a little:

> Added constructors. I think it's cleaner this way.

This class is called back by Arquillian and not really intended to be instantiated directly. It doesn't really *need* such constructor. When Piranha Micro commandline starts this code may change quite a bit though.

> Used this. in every place where attributes are being used.

I realise we hadn't published our code conventions yet, but that is unfortunately against the convention. I just published it here: https://github.com/piranhacloud/piranha/wiki/code-conventions

The usage of `final` in the method parameters is unfortunately against the conventions as well.

> Renamed lambda variables from e to what they actually are.

Thanks, that's fine, though do note that just like in loops with `i` and `j`, `e` can be acceptable in lambdas if it's clear enough what it is (making that an exception to the general rule).

>  The validate() method doesn't actually do any validations from what I can see. It's actually an init method :)

That's an Arquillian thing, it's the one moment where you can initialise. If I'm not mistaken more Arquillian containers do it that way.

**Comment by amihaiemil** [comment]
@arjantijms Thanks. I like the code guidelines. May I however suggest that the maximum line length be 80 chars instead of 160? 

And regarding this PR: 

- I will remove the ``this.`` and ``final`` stuff
- should I also remove the constructors? 
- about the lambda naming: I renamed the ``e`` because there are more lambdas in that validate function and it was hard for me to follow which ``e`` is which. Can I leave it like this?

**Comment by amihaiemil** [comment]
@arjantijms any updates here? I think I addressed your comments :D

**Comment by manorrock** [comment]
@amihaiemil Can you please resolved the conflicts?

**Comment by amihaiemil** [comment]
@manorrock Done. Sorry for the delayed answer :)

**Comment by mnriem** [comment]
@amihaiemil As we are preparing for moving the codebase of Piranha into its own foundation we need to make sure we properly account for any code contribution. I know this is a pretty old contribution, but can you please acknowledge that any of your code contributions (past, current and future) are owned by Manorrock.com and it can do with them as it sees fit? Thanks!

**Comment by amihaiemil** [comment]
@amihaiemil of course! All my contributions here are the property of the repo's owner.

**Comment by mnriem** [comment]
Thank you for the prompt response!

**Pull request merged**
