### PR TITLE
Fixes issue #745 - WebXmlProcessor.processFilterMappings is adding ServletMapping

### PR DESCRIPTION
**Pull request by Thihup**

### CODE REVIEW

**Comment by manorrock** [comment]
As this is your first PR can you please acknowledge that the code will be owned by Manorrock.com. I will only ask this one time as that is all that is needed for contributing code back to us.

And can you remove the changes on the header as they are unnecessary.

Thank you for finding the issue and issuing your first PR.

**Comment by Thihup** [comment]
Alright!

Thanks.

**Comment by manorrock** [comment]
And the acknowledgement?

**Comment by Thihup** [comment]
I agree with the acknowledgement.

Em dom, 17 de mai de 2020 14:21, manorrock <notifications@github.com>
escreveu:

**Pull request merged**
